### PR TITLE
Added SVG export support for the OrigamiModel and refactored all SVG exports

### PR DESCRIPTION
**Pull request by JinoBetti**

### CODE REVIEW

**Review by Ooouch1 — CHANGES_REQUESTED** [review]
I like your changes but the export of folded model (an existing functionality) is broken. Can you fix it?

**Comment by JinoBetti** [comment]
Of course I'll fix it, Indeed I tested with a very simple case and didn't see that the result was wrong... gomen !

**Comment by JinoBetti** [comment]
That should do it, there were two mistakes : I wasn't passing the sorted faces to the converter so the faces were in no particular order, and I forgot to take the faceOrderFlip parameter into account, reversing the order if necessary.
Now I've got the same results as before, wether it's flipped or not.

**Review by Ooouch1 — APPROVED** [review]
Bug fix.

**Pull request merged**
