### PR TITLE
Java Doc

### PR DESCRIPTION
**Pull request by lifesbest23**
I started adding more java doc comments, not sure if they are all that helpful but I tried to keep it short while writing to most public functions something (for InitData object handling classes so far only though).
Not sure if you prefer some specific way of writing javaDoc, or even how you handle Branches and version numbers, if that is the case I would be happy to adjust to that.

### CODE REVIEW

**Comment by Ooouch1** [comment]
Handling branches is a difficult issue for me because I don't have much experience about that.
However, I'm afraid that merging to master is not the way to go in this pull request.
If we do that, the master branch will include the codes in development written by me. it's not a preferred state as master.

Your branch seems to be created from v1.40 branch,
so how about merging your branch to v1.40?

I'm glad that you are interested in ORIPA's development.

**Comment by lifesbest23** [comment]
I am also new to project management but your suggestion sound reasonable. I have a fix for #71 should I add it to this pull request or make a seperate one?

**Comment by Ooouch1** [comment]
I think a fix of #71 is to be separated. It's a matter different to documentation.

**Comment by lifesbest23** [comment]
I am following the changes you make for a few month now and am thankful for the refactoring you started as I found some things quite irritating in the beginning.
I hope that the better javadoc helps future people interested in this project like me to get started.

**Pull request merged**
