### PR TITLE
Geometry performance improvements

### PR DESCRIPTION
**Pull request by mkosmul**

### CODE REVIEW

**Comment by mkosmul** [comment]
Performance optimization and added tests for Matrix2d and Vector2d

**Comment by mkosmul** [comment]
Besides the changes in this PR, I also tried a number of different improvements, but they didn't give any measurable improvement, at least for my test case, and some even decreased performance significantly. In no particular order:

- inlining and simplifying `Matrix2d().isRegular()`
- replacing all calls to `cos`, `sin`, and `sqrt` from the standard library with their equivalents from `commons-math3` FastMath
- replacing various `HashSet<Integer>` used in folding algorithm with other implementations: `TreeSet`, `BitSet`, various implementations of `IntSet` from FastUtil

**Comment by Ooouch1** [comment]
A little hard to see the changes from the previous PR #390 since this PR has the same commits.
I'm glad if you can fix it. (merge the master or re-create PR based on the latest master, maybe?)

**Comment by mkosmul** [comment]
Closing in order to open new PR relative to the new master branch

**Pull request closed without merging**
