### PR TITLE
Aux lines are collapsed into the folded model like precreases

### PR DESCRIPTION
**Pull request by undertrox**
Only works for the SVG export, which also groups the faces with their precreases. This could be very useful for people who are diagramming models.

### CODE REVIEW

**Review by Ooouch1 — COMMENTED** [review]
Basically good.

**Comment by undertrox** [comment]
I'm sorry for adding another functionality commit after your review, I didn't check to see if you reviewed already before pushing. 
The problem was that, if there were no creases, only cut lines, the origamiModel would not have any faces and therefore could not be folded. My solution only works for convex papers, but I believe that should be enough

**Comment by Ooouch1** [comment]
Confirmed. Cool. If there is nothing to add, I will merge later.

**Comment by undertrox** [comment]
Nice, thank you

**Pull request merged**
