### PR TITLE
made project compile with gradle, made 'gradle run' work

### PR DESCRIPTION
**Pull request by DrTTom**
I'm very interested in drawing origami patterns and would like to see this project grow.

### CODE REVIEW

**Comment by DrTTom** [comment]
Please consider using Java 11 instead of 7, it would make things much easier.

**Comment by Ooouch1** [comment]
Thank you for committing. 
Sorry that I made huge conflicts but I would think my commits make this project substantially better.
It seems too hard to fix the conflicts, so may I dismiss your commits?
I apologize that I didn't merge my old branch before you touch this project.

I would like to accept the change on gradle at least but I don't know how.

I agree that we should introduce Java 11 since Java 7 is out of support by Oracle.

I wish your further contribution.

**Comment by Ooouch1** [comment]
> I would appreciate if you could leave the pull request as it is for the time being, 
> I will pull the changes into my branch and handle the conflicts there using some tool support. 
That's great.  I will keep this pull request open.

**Comment by gerasdf** [comment]
Hi! I have been maintaining my own version of Oripa, even from before the original source code was available. I have implemented some new commands and features, and I'd like to contribute. But I have problems compiling. I tried DrTTom's master also with no luck. I'm very happy to see movement here. If I could contribute to help things compile in latest linuxes, I'll try to do, but I don't understand gradle, so I'm stuck... please, let me know how can I help

**Comment by Ooouch1** [comment]
Actually I'm not a user of gradle. I use maven (which requires pom.xml) on Eclipse IDE, and that works fine for me. My OS is Windows 10. You can try it by cloning java11 branch of our repository (https://github.com/oripa/oripa/tree/java11). 

If you like to use gradle, what I can suggest is:
* Use the latest version of gradle. I think you have to check which version of Java is supported by gradle as well.
* Confirm that you have set the PATH (or JAVA_HOME) correctly.
* I'm not sure how your compiling fails. Does Java compiler command work? You mean that gradle runs but fails on compiling phase? Or gradle does not work at all?

**Comment by Ooouch1** [comment]
I'd like to close this PR because I switched to use gradle with Kotlin DSL in #372 .

**Pull request closed without merging**
